version: "3.8"

volumes:
    mysql_data:
      driver: local

services:
  mysql:
    image: mysql:latest
    container_name: mysql-dev
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - TZ=America/Sao_Paulo
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
  